name: Build

on: ["push", "pull_request"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Execute tests and compute coverage
        run: mvn clean test
      - name: Generate coverage report
        run: mvn jacoco:report
      - name: Coveralls
         uses: coverallsapp/github-action@master
         with:
         github-token: ${{ secrets.GITHUB_TOKEN }}
